### ISSUE TITLE
How do i use it ?

### ISSUE THREAD

**Issue by LOLZ1235** [davidjcralph/kaomoji#4]
How do i use it ?

**Comment by davidjcralph** [comment]
Simply run  ``.kaomoji joy <text here>`` and it will send your message with a random kaomoji from the joy category at the end of it.

After typing .kaomoji or .kao, the autocomplete prompt will show the list of available emote types or you can check the  README.

Note that if you use a command prefix different to the default you should replace the . with that prefix.
